analyzer:
  errors:
    prefer_interpolation_to_compose_strings: ignore
    sort_constructors_first: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
